spring.application.name=ai-chatbot
spring.datasource.url=jdbc:postgresql://localhost:5432/ai-chatbot
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.session.jdbc.initialize-schema=always
spring.jpa.show-sql=true
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=phi3:mini

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nirmalkrupa2006@gmail.com
spring.mail.password=ierimveqpoyyeezm

spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true